//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Labels", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddItem.
        /// </summary>
        internal static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Department.
        /// </summary>
        internal static string AddNewDepartment {
            get {
                return ResourceManager.GetString("AddNewDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Item Category.
        /// </summary>
        internal static string AddNewItemCategory {
            get {
                return ResourceManager.GetString("AddNewItemCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Item Group.
        /// </summary>
        internal static string AddNewItemGroup {
            get {
                return ResourceManager.GetString("AddNewItemGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Record.
        /// </summary>
        internal static string AddNewRecord {
            get {
                return ResourceManager.GetString("AddNewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Role.
        /// </summary>
        internal static string AddNewRole {
            get {
                return ResourceManager.GetString("AddNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Consume Form.
        /// </summary>
        internal static string add_consume_pc10 {
            get {
                return ResourceManager.GetString("add_consume_pc10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Country.
        /// </summary>
        internal static string add_country {
            get {
                return ResourceManager.GetString("add_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add District.
        /// </summary>
        internal static string add_district {
            get {
                return ResourceManager.GetString("add_district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Lookup Type.
        /// </summary>
        internal static string add_lookup_type {
            get {
                return ResourceManager.GetString("add_lookup_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Lookup Value.
        /// </summary>
        internal static string add_lookup_value {
            get {
                return ResourceManager.GetString("add_lookup_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Province.
        /// </summary>
        internal static string add_province {
            get {
                return ResourceManager.GetString("add_province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Restore.
        /// </summary>
        internal static string add_restore_form {
            get {
                return ResourceManager.GetString("add_restore_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        internal static string add_user {
            get {
                return ResourceManager.GetString("add_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Value.
        /// </summary>
        internal static string add_value {
            get {
                return ResourceManager.GetString("add_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string ADMIN {
            get {
                return ResourceManager.GetString("ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string administration {
            get {
                return ResourceManager.GetString("administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Stockin.
        /// </summary>
        internal static string all_stockin {
            get {
                return ResourceManager.GetString("all_stockin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string any {
            get {
                return ResourceManager.GetString("any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string are_you_sure {
            get {
                return ResourceManager.GetString("are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        internal static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Quantity.
        /// </summary>
        internal static string Available_Quantity {
            get {
                return ResourceManager.GetString("Available_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string back_to_list {
            get {
                return ResourceManager.GetString("back_to_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Code.
        /// </summary>
        internal static string Bar_Code {
            get {
                return ResourceManager.GetString("Bar_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiary.
        /// </summary>
        internal static string beneficiary {
            get {
                return ResourceManager.GetString("beneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        internal static string Box {
            get {
                return ResourceManager.GetString("Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name.
        /// </summary>
        internal static string BranchName {
            get {
                return ResourceManager.GetString("BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Office.
        /// </summary>
        internal static string branch_office {
            get {
                return ResourceManager.GetString("branch_office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinet.
        /// </summary>
        internal static string Cabinet {
            get {
                return ResourceManager.GetString("Cabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string change_pass {
            get {
                return ResourceManager.GetString("change_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Reports.
        /// </summary>
        internal static string ChartReports {
            get {
                return ResourceManager.GetString("ChartReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check item availabe quanity and try again..
        /// </summary>
        internal static string check_available_quantity_try_again {
            get {
                return ResourceManager.GetString("check_available_quantity_try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an option.
        /// </summary>
        internal static string choose_an_option {
            get {
                return ResourceManager.GetString("choose_an_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse Panels.
        /// </summary>
        internal static string collapse_panels {
            get {
                return ResourceManager.GetString("collapse_panels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commissions.
        /// </summary>
        internal static string commissions {
            get {
                return ResourceManager.GetString("commissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm does not match!.
        /// </summary>
        internal static string confirm_does_not_match {
            get {
                return ResourceManager.GetString("confirm_does_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor Name.
        /// </summary>
        internal static string Contractor_Name {
            get {
                return ResourceManager.GetString("Contractor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Cooridnates!.
        /// </summary>
        internal static string coordinate_duplicate {
            get {
                return ResourceManager.GetString("coordinate_duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country List.
        /// </summary>
        internal static string country_list {
            get {
                return ResourceManager.GetString("country_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Lookup.
        /// </summary>
        internal static string country_lkp {
            get {
                return ResourceManager.GetString("country_lkp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County/District.
        /// </summary>
        internal static string county_city {
            get {
                return ResourceManager.GetString("county_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentProvince.
        /// </summary>
        internal static string CurrentProvince {
            get {
                return ResourceManager.GetString("CurrentProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string curr_pass {
            get {
                return ResourceManager.GetString("curr_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is wrong!.
        /// </summary>
        internal static string curr_pass_wrong {
            get {
                return ResourceManager.GetString("curr_pass_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dari.
        /// </summary>
        internal static string dari {
            get {
                return ResourceManager.GetString("dari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dari Name.
        /// </summary>
        internal static string dari_name {
            get {
                return ResourceManager.GetString("dari_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Expired.
        /// </summary>
        internal static string date_expired {
            get {
                return ResourceManager.GetString("date_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal With Account.
        /// </summary>
        internal static string DealWithAccount {
            get {
                return ResourceManager.GetString("DealWithAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliver By.
        /// </summary>
        internal static string DeliverBy {
            get {
                return ResourceManager.GetString("DeliverBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered Date.
        /// </summary>
        internal static string DeliveredDate {
            get {
                return ResourceManager.GetString("DeliveredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Place.
        /// </summary>
        internal static string DeliveryPlace {
            get {
                return ResourceManager.GetString("DeliveryPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Report.
        /// </summary>
        internal static string detailed_report {
            get {
                return ResourceManager.GetString("detailed_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaced Province.
        /// </summary>
        internal static string DisplacedProvince {
            get {
                return ResourceManager.GetString("DisplacedProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        internal static string display_name {
            get {
                return ResourceManager.GetString("display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Ticket.
        /// </summary>
        internal static string DistributionTicket {
            get {
                return ResourceManager.GetString("DistributionTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Ticket List.
        /// </summary>
        internal static string DistributionTicketList {
            get {
                return ResourceManager.GetString("DistributionTicketList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string district {
            get {
                return ResourceManager.GetString("district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District Code.
        /// </summary>
        internal static string district_code {
            get {
                return ResourceManager.GetString("district_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District List.
        /// </summary>
        internal static string district_list {
            get {
                return ResourceManager.GetString("district_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District Lookup.
        /// </summary>
        internal static string district_lkp {
            get {
                return ResourceManager.GetString("district_lkp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Information.
        /// </summary>
        internal static string DocumentInfo {
            get {
                return ResourceManager.GetString("DocumentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Number.
        /// </summary>
        internal static string DocumentNumber {
            get {
                return ResourceManager.GetString("DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Prveview.
        /// </summary>
        internal static string DocumentPrveview {
            get {
                return ResourceManager.GetString("DocumentPrveview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document State.
        /// </summary>
        internal static string DocumentState {
            get {
                return ResourceManager.GetString("DocumentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Text.
        /// </summary>
        internal static string DocumentText {
            get {
                return ResourceManager.GetString("DocumentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate of Refugees and Repatriations.
        /// </summary>
        internal static string dorr {
            get {
                return ResourceManager.GetString("dorr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Code.
        /// </summary>
        internal static string duplicate_code {
            get {
                return ResourceManager.GetString("duplicate_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Reg No.
        /// </summary>
        internal static string duplicate_reg_no {
            get {
                return ResourceManager.GetString("duplicate_reg_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string EDITOR {
            get {
                return ResourceManager.GetString("EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Case.
        /// </summary>
        internal static string edit_case {
            get {
                return ResourceManager.GetString("edit_case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Consumption Form PC-10.
        /// </summary>
        internal static string edit_consume_pc10 {
            get {
                return ResourceManager.GetString("edit_consume_pc10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Restore Form.
        /// </summary>
        internal static string edit_restore_form {
            get {
                return ResourceManager.GetString("edit_restore_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Information.
        /// </summary>
        internal static string EmployeeInfo {
            get {
                return ResourceManager.GetString("EmployeeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee List.
        /// </summary>
        internal static string EmployeeList {
            get {
                return ResourceManager.GetString("EmployeeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        internal static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        internal static string english_name {
            get {
                return ResourceManager.GetString("english_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterance Date.
        /// </summary>
        internal static string EnteranceDate {
            get {
                return ResourceManager.GetString("EnteranceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Role Name.
        /// </summary>
        internal static string EnterRoleName {
            get {
                return ResourceManager.GetString("EnterRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Country Name.
        /// </summary>
        internal static string enter_country_name {
            get {
                return ResourceManager.GetString("enter_country_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter District Name.
        /// </summary>
        internal static string enter_district_name {
            get {
                return ResourceManager.GetString("enter_district_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Province Name.
        /// </summary>
        internal static string enter_province_name {
            get {
                return ResourceManager.GetString("enter_province_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Village Name.
        /// </summary>
        internal static string enter_village_name {
            get {
                return ResourceManager.GetString("enter_village_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured.
        /// </summary>
        internal static string error_occured {
            get {
                return ResourceManager.GetString("error_occured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Panels.
        /// </summary>
        internal static string expand_panels {
            get {
                return ResourceManager.GetString("expand_panels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        internal static string export_excel {
            get {
                return ResourceManager.GetString("export_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to PDF.
        /// </summary>
        internal static string export_pdf {
            get {
                return ResourceManager.GetString("export_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Name.
        /// </summary>
        internal static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final scan.
        /// </summary>
        internal static string FinalSOAttachment {
            get {
                return ResourceManager.GetString("FinalSOAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string first {
            get {
                return ResourceManager.GetString("first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Information.
        /// </summary>
        internal static string FormInfo {
            get {
                return ResourceManager.GetString("FormInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Control.
        /// </summary>
        internal static string FullControl {
            get {
                return ResourceManager.GetString("FullControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Figures.
        /// </summary>
        internal static string GeneralFigures {
            get {
                return ResourceManager.GetString("GeneralFigures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Lookups.
        /// </summary>
        internal static string general_lookups {
            get {
                return ResourceManager.GetString("general_lookups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify.
        /// </summary>
        internal static string identify {
            get {
                return ResourceManager.GetString("identify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        internal static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming.
        /// </summary>
        internal static string Incoming {
            get {
                return ResourceManager.GetString("Incoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information inserted successfully!.
        /// </summary>
        internal static string info_insert_suc {
            get {
                return ResourceManager.GetString("info_insert_suc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information updated successfully!.
        /// </summary>
        internal static string info_update_suc {
            get {
                return ResourceManager.GetString("info_update_suc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted By.
        /// </summary>
        internal static string inserted_by {
            get {
                return ResourceManager.GetString("inserted_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted Date.
        /// </summary>
        internal static string inserted_date {
            get {
                return ResourceManager.GetString("inserted_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username!.
        /// </summary>
        internal static string invalid_username {
            get {
                return ResourceManager.GetString("invalid_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islamic Republic of Afghanistan.
        /// </summary>
        internal static string ira {
            get {
                return ResourceManager.GetString("ira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Related to Previous Document.
        /// </summary>
        internal static string IsRelated {
            get {
                return ResourceManager.GetString("IsRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Related.
        /// </summary>
        internal static string IsRelatedH {
            get {
                return ResourceManager.GetString("IsRelatedH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Sent.
        /// </summary>
        internal static string IsSent {
            get {
                return ResourceManager.GetString("IsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued.
        /// </summary>
        internal static string Issued {
            get {
                return ResourceManager.GetString("Issued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        internal static string IssueDate {
            get {
                return ResourceManager.GetString("IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Number.
        /// </summary>
        internal static string issue_number {
            get {
                return ResourceManager.GetString("issue_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Expired.
        /// </summary>
        internal static string is_expired {
            get {
                return ResourceManager.GetString("is_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Second Hand.
        /// </summary>
        internal static string is_second_hand {
            get {
                return ResourceManager.GetString("is_second_hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Condition.
        /// </summary>
        internal static string ItemCodition {
            get {
                return ResourceManager.GetString("ItemCodition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item In Use.
        /// </summary>
        internal static string ItemInUse {
            get {
                return ResourceManager.GetString("ItemInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item In Warehouse.
        /// </summary>
        internal static string ItemInWarehouse {
            get {
                return ResourceManager.GetString("ItemInWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items To Be Retored.
        /// </summary>
        internal static string ItemsTobeRestored {
            get {
                return ResourceManager.GetString("ItemsTobeRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item already exist.
        /// </summary>
        internal static string Item_already_exist {
            get {
                return ResourceManager.GetString("Item_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Category.
        /// </summary>
        internal static string Item_Category {
            get {
                return ResourceManager.GetString("Item_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        internal static string Item_Code {
            get {
                return ResourceManager.GetString("Item_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Consumed Search.
        /// </summary>
        internal static string item_consumed_search {
            get {
                return ResourceManager.GetString("item_consumed_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Group.
        /// </summary>
        internal static string Item_Group {
            get {
                return ResourceManager.GetString("Item_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string Item_Name {
            get {
                return ResourceManager.GetString("Item_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land Claims.
        /// </summary>
        internal static string land_claims {
            get {
                return ResourceManager.GetString("land_claims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string last {
            get {
                return ResourceManager.GetString("last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified By.
        /// </summary>
        internal static string last_modified_by {
            get {
                return ResourceManager.GetString("last_modified_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified Date.
        /// </summary>
        internal static string last_modified_date {
            get {
                return ResourceManager.GetString("last_modified_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string left {
            get {
                return ResourceManager.GetString("left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Records.
        /// </summary>
        internal static string ListOfRecords {
            get {
                return ResourceManager.GetString("ListOfRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Roles.
        /// </summary>
        internal static string ListOfRoles {
            get {
                return ResourceManager.GetString("ListOfRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of ticket.
        /// </summary>
        internal static string List_of_ticket {
            get {
                return ResourceManager.GetString("List_of_ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to System.
        /// </summary>
        internal static string login_to_system {
            get {
                return ResourceManager.GetString("login_to_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup Name.
        /// </summary>
        internal static string LookupName {
            get {
                return ResourceManager.GetString("LookupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookups.
        /// </summary>
        internal static string lookups {
            get {
                return ResourceManager.GetString("lookups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup data updated. System is ready to use..
        /// </summary>
        internal static string LookupSyncMsg {
            get {
                return ResourceManager.GetString("LookupSyncMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup Types.
        /// </summary>
        internal static string lookup_types {
            get {
                return ResourceManager.GetString("lookup_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup Values.
        /// </summary>
        internal static string lookup_values {
            get {
                return ResourceManager.GetString("lookup_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mem 3/2  Date.
        /// </summary>
        internal static string Mem2or3Date {
            get {
                return ResourceManager.GetString("Mem2or3Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mem 7 Form.
        /// </summary>
        internal static string Mem7Form {
            get {
                return ResourceManager.GetString("Mem7Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minister.
        /// </summary>
        internal static string Minister {
            get {
                return ResourceManager.GetString("Minister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        internal static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry of Refugees and Repatriations.
        /// </summary>
        internal static string morr {
            get {
                return ResourceManager.GetString("morr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string new_pass {
            get {
                return ResourceManager.GetString("new_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items Found.
        /// </summary>
        internal static string NoItemFound {
            get {
                return ResourceManager.GetString("NoItemFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This person is not registered.
        /// </summary>
        internal static string not_identified {
            get {
                return ResourceManager.GetString("not_identified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number in Box.
        /// </summary>
        internal static string NumberInBox {
            get {
                return ResourceManager.GetString("NumberInBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Only!.
        /// </summary>
        internal static string number_only {
            get {
                return ResourceManager.GetString("number_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained From Contractor.
        /// </summary>
        internal static string ObtainedFromContractor {
            get {
                return ResourceManager.GetString("ObtainedFromContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        internal static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original district.
        /// </summary>
        internal static string oDistrict {
            get {
                return ResourceManager.GetString("oDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation done successfully!.
        /// </summary>
        internal static string operation_done_suc {
            get {
                return ResourceManager.GetString("operation_done_suc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original province.
        /// </summary>
        internal static string oProvince {
            get {
                return ResourceManager.GetString("oProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order By.
        /// </summary>
        internal static string OrderBy {
            get {
                return ResourceManager.GetString("OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        internal static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        internal static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Text.
        /// </summary>
        internal static string OrderText {
            get {
                return ResourceManager.GetString("OrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string organization {
            get {
                return ResourceManager.GetString("organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        internal static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string OTH {
            get {
                return ResourceManager.GetString("OTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Countries.
        /// </summary>
        internal static string OtherCountries {
            get {
                return ResourceManager.GetString("OtherCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pashto.
        /// </summary>
        internal static string pashto {
            get {
                return ResourceManager.GetString("pashto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pashtu Name.
        /// </summary>
        internal static string pashtu_name {
            get {
                return ResourceManager.GetString("pashtu_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully!.
        /// </summary>
        internal static string pass_change_suc {
            get {
                return ResourceManager.GetString("pass_change_suc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string pass_conf {
            get {
                return ResourceManager.GetString("pass_conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be combination of upper case,  lower case,  numbers and special symbols!.
        /// </summary>
        internal static string pass_error {
            get {
                return ResourceManager.GetString("pass_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC 10 Form.
        /// </summary>
        internal static string PC10Form {
            get {
                return ResourceManager.GetString("PC10Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P-C-5 Form.
        /// </summary>
        internal static string PC5Form {
            get {
                return ResourceManager.GetString("PC5Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one of checkboxes.
        /// </summary>
        internal static string PleaseSelectCheckbox {
            get {
                return ResourceManager.GetString("PleaseSelectCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add item.
        /// </summary>
        internal static string please_add_item {
            get {
                return ResourceManager.GetString("please_add_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Please Select--.
        /// </summary>
        internal static string please_select {
            get {
                return ResourceManager.GetString("please_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select employee.
        /// </summary>
        internal static string please_select_employee {
            get {
                return ResourceManager.GetString("please_select_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select item.
        /// </summary>
        internal static string please_select_item {
            get {
                return ResourceManager.GetString("please_select_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Preview.
        /// </summary>
        internal static string print_preview {
            get {
                return ResourceManager.GetString("print_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string province {
            get {
                return ResourceManager.GetString("province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Code.
        /// </summary>
        internal static string province_code {
            get {
                return ResourceManager.GetString("province_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province List.
        /// </summary>
        internal static string province_list {
            get {
                return ResourceManager.GetString("province_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Lookup.
        /// </summary>
        internal static string province_lkp {
            get {
                return ResourceManager.GetString("province_lkp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province/State.
        /// </summary>
        internal static string province_state {
            get {
                return ResourceManager.GetString("province_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Consumed.
        /// </summary>
        internal static string quantity_consumed {
            get {
                return ResourceManager.GetString("quantity_consumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Date.
        /// </summary>
        internal static string ReceiptDate {
            get {
                return ResourceManager.GetString("ReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Report( M7 form).
        /// </summary>
        internal static string ReceiptReport {
            get {
                return ResourceManager.GetString("ReceiptReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Report Information.
        /// </summary>
        internal static string ReceiptReportInfo {
            get {
                return ResourceManager.GetString("ReceiptReportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Report Items.
        /// </summary>
        internal static string ReceiptReportItems {
            get {
                return ResourceManager.GetString("ReceiptReportItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revceive Date.
        /// </summary>
        internal static string ReceiveDate {
            get {
                return ResourceManager.GetString("ReceiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Date.
        /// </summary>
        internal static string RecordDate {
            get {
                return ResourceManager.GetString("RecordDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records Per Page.
        /// </summary>
        internal static string RecordsPerPage {
            get {
                return ResourceManager.GetString("RecordsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Type.
        /// </summary>
        internal static string RegistrationType {
            get {
                return ResourceManager.GetString("RegistrationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Information.
        /// </summary>
        internal static string registration_info {
            get {
                return ResourceManager.GetString("registration_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Document Number.
        /// </summary>
        internal static string RelatedDocNumber {
            get {
                return ResourceManager.GetString("RelatedDocNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Number.
        /// </summary>
        internal static string RelatedNumberH {
            get {
                return ResourceManager.GetString("RelatedNumberH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report User.
        /// </summary>
        internal static string REPORT {
            get {
                return ResourceManager.GetString("REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Number.
        /// </summary>
        internal static string ReportNumber {
            get {
                return ResourceManager.GetString("ReportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        internal static string RequestDate {
            get {
                return ResourceManager.GetString("RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester.
        /// </summary>
        internal static string Requester {
            get {
                return ResourceManager.GetString("Requester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester Information.
        /// </summary>
        internal static string Requester_Information {
            get {
                return ResourceManager.GetString("Requester_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Number.
        /// </summary>
        internal static string RequestNumber {
            get {
                return ResourceManager.GetString("RequestNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string restore {
            get {
                return ResourceManager.GetString("restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore By Information.
        /// </summary>
        internal static string RestoreByInfo {
            get {
                return ResourceManager.GetString("RestoreByInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restored Items.
        /// </summary>
        internal static string Restored_items {
            get {
                return ResourceManager.GetString("Restored_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restored Items List.
        /// </summary>
        internal static string Restored_items_list {
            get {
                return ResourceManager.GetString("Restored_items_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Form.
        /// </summary>
        internal static string restore_form {
            get {
                return ResourceManager.GetString("restore_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Date.
        /// </summary>
        internal static string ReturnDate {
            get {
                return ResourceManager.GetString("ReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Item.
        /// </summary>
        internal static string return_item {
            get {
                return ResourceManager.GetString("return_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string right {
            get {
                return ResourceManager.GetString("right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role ID.
        /// </summary>
        internal static string RoleID {
            get {
                return ResourceManager.GetString("RoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Management.
        /// </summary>
        internal static string RoleMgt {
            get {
                return ResourceManager.GetString("RoleMgt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        internal static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Preview.
        /// </summary>
        internal static string ScanPreview {
            get {
                return ResourceManager.GetString("ScanPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Archived Document.
        /// </summary>
        internal static string SearchArchivedDocument {
            get {
                return ResourceManager.GetString("SearchArchivedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Report.
        /// </summary>
        internal static string SearchReport {
            get {
                return ResourceManager.GetString("SearchReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Ticket.
        /// </summary>
        internal static string SearchTicket {
            get {
                return ResourceManager.GetString("SearchTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Criteria.
        /// </summary>
        internal static string search_criteria {
            get {
                return ResourceManager.GetString("search_criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Hand Price.
        /// </summary>
        internal static string second_hand_price {
            get {
                return ResourceManager.GetString("second_hand_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Select Department ---.
        /// </summary>
        internal static string Select_Department {
            get {
                return ResourceManager.GetString("Select_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select District--.
        /// </summary>
        internal static string select_district {
            get {
                return ResourceManager.GetString("select_district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Employee.
        /// </summary>
        internal static string Select_Employee {
            get {
                return ResourceManager.GetString("Select_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select Province--.
        /// </summary>
        internal static string select_province {
            get {
                return ResourceManager.GetString("select_province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        internal static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent By.
        /// </summary>
        internal static string SentTo {
            get {
                return ResourceManager.GetString("SentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial #.
        /// </summary>
        internal static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf.
        /// </summary>
        internal static string Shelf {
            get {
                return ResourceManager.GetString("Shelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock in Date.
        /// </summary>
        internal static string StockInDate {
            get {
                return ResourceManager.GetString("StockInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ind_not_allowed_err.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmissionDate.
        /// </summary>
        internal static string SubmissionDate {
            get {
                return ResourceManager.GetString("SubmissionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion Bill Number.
        /// </summary>
        internal static string SuggestionBillNumber {
            get {
                return ResourceManager.GetString("SuggestionBillNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Report.
        /// </summary>
        internal static string summary_report {
            get {
                return ResourceManager.GetString("summary_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super User.
        /// </summary>
        internal static string SUPER {
            get {
                return ResourceManager.GetString("SUPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System For MoRR Inventory.
        /// </summary>
        internal static string SystemForInventory {
            get {
                return ResourceManager.GetString("SystemForInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information About System.
        /// </summary>
        internal static string SystemInfo {
            get {
                return ResourceManager.GetString("SystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID Number.
        /// </summary>
        internal static string Tazkira {
            get {
                return ResourceManager.GetString("Tazkira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Only!.
        /// </summary>
        internal static string text_only {
            get {
                return ResourceManager.GetString("text_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket &amp; Request Information.
        /// </summary>
        internal static string TicketAndRequestInfo {
            get {
                return ResourceManager.GetString("TicketAndRequestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Issued Date.
        /// </summary>
        internal static string TicketIssedDate {
            get {
                return ResourceManager.GetString("TicketIssedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Items.
        /// </summary>
        internal static string TicketItems {
            get {
                return ResourceManager.GetString("TicketItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Number.
        /// </summary>
        internal static string TicketNumber {
            get {
                return ResourceManager.GetString("TicketNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Of Document.
        /// </summary>
        internal static string TypeOfDocument {
            get {
                return ResourceManager.GetString("TypeOfDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type new password:.
        /// </summary>
        internal static string type_new_pass {
            get {
                return ResourceManager.GetString("type_new_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update User Role.
        /// </summary>
        internal static string UnableToUpdateRole {
            get {
                return ResourceManager.GetString("UnableToUpdateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to insert information!.
        /// </summary>
        internal static string unable_to_insert {
            get {
                return ResourceManager.GetString("unable_to_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update information!.
        /// </summary>
        internal static string unable_to_update {
            get {
                return ResourceManager.GetString("unable_to_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to upload image.
        /// </summary>
        internal static string Unable_to_upload_image {
            get {
                return ResourceManager.GetString("Unable_to_upload_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        internal static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Type.
        /// </summary>
        internal static string Usage_Type {
            get {
                return ResourceManager.GetString("Usage_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists!.
        /// </summary>
        internal static string username_already_exists {
            get {
                return ResourceManager.GetString("username_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role updated successfully.
        /// </summary>
        internal static string UserRoleUpdatedSuc {
            get {
                return ResourceManager.GetString("UserRoleUpdatedSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string user_management {
            get {
                return ResourceManager.GetString("user_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert Username and Password!.
        /// </summary>
        internal static string user_pass_req {
            get {
                return ResourceManager.GetString("user_pass_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Password is wrong!.
        /// </summary>
        internal static string user_pass_wrong {
            get {
                return ResourceManager.GetString("user_pass_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        internal static string values {
            get {
                return ResourceManager.GetString("values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Form.
        /// </summary>
        internal static string View_Form {
            get {
                return ResourceManager.GetString("View_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        internal static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
